spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.202.250.117:3306/be6_aa_coupon_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ps
    password: ${DB_MQ_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  instance:
    instance-id: coupon-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka

api:
  gateway:
    host: localhost
    port: 8000
