POST http://localhost:8091/api/coupons/policies
Content-Type: application/json

{
  "name": "카테고리 쿠폰",
  "discountType": "rate",
  "discountRate": 0.2,
  "discountAmount": 0,
  "standardPrice": 10000,
  "maxDiscountAmount": 20000,
  "period": 14,
  "startDate": "2024-06-23",
  "endDate": "2024-06-25",
  "couponType": "category",
  "targetId": -1
}

###
GET http://localhost:8091/api/coupons/policies?scope=global,book,category