name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yaml
        env:
          spring.datasource.password: ${{ secrets.DB_MQ_PASSWORD }}
          spring.rabbitmq.password: ${{ secrets.DB_MQ_PASSWORD }}
      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: upload file
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "target/*.jar"
          target: "~/coupon/"
          rm: false
      - name: execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            chmod 755 ~/coupon/target/coupon-0.0.1-SNAPSHOT.jar
            ./coupon/deploy.sh
